name: ripetute
description: Traccia i tuoi allenamenti in arrampicata

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayer: 0.8.1
  audioplayer_web:
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  intl: ^0.16.0
  shared_preferences: ^0.5.7+3
  introduction_screen: ^1.0.7
  fl_chart: ^0.30.0
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
#  flutter_launcher_icons:
#
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: assets\icon.png

flutter:
  assets:
    - assets\start.png
    - assets\timer.png
    - assets\stat.png
    - assets\end.png
    - assets\share.png
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
